local controls_simple = require(game.ReplicatedStorage.Shared.controls_simple)
local GGPO = require(game.ReplicatedStorage.Shared.ggpo)

return function()
    describe("SimpleControls", function()
        it("basic", function()
            local controls = controls_simple.SimpleControls_new()
            expect(controls.left).to.equal(false)
            expect(controls.right).to.equal(false)
            expect(controls.up).to.equal(false)
            expect(controls.down).to.equal(false)
            expect(controls.a).to.equal(false)
            expect(controls.b).to.equal(false)
            expect(controls.x).to.equal(false)
            expect(controls.y).to.equal(false)
        end)
        it("typeof does not do what I want it to do :(", function()
            local controls = controls_simple.SimpleControls_new()
            expect(typeof(controls)).to.equal("table")
        end)
    end)
end